### ISSUE TITLE
Supported weights file for Forge

### ISSUE THREAD

**Issue by ankghost0912** [hollance/Forge#2]
Hi, 

I wanted to know if `.bin` or `.dat` are the only file types supported, for interacting with the Forge framework. Can Forge work with files like `.caffemodel` or `.pb` or with files which do not specify weights and biases for every layer?

If `.bin` or `.dat` are the only supported file types, are you aware of any conversion tools to convert from other binary weight file types?

Thanks

**Comment by hollance** [comment]
In theory Forge can support any file type because you can write your own implementation of `ParameterData`, which is used to load the weights.

Using the built-in `ParameterLoaderBundle` object, the weights are expected to be binary files with raw 32-bit floats inside them. Metal also expects the weights to be in a specific order.

Using a caffemodel file would require loading the weights, transposing them in memory, and then giving them to Metal. It's possible but not as efficient as converting the weights once beforehand storing them in a .bin file.

(By the way, .bin and .dat are the same file format: just binary float values.)

I have a few conversion scripts from caffemodel, h5, TensorFlow graph defs etc, but these need to be tweaked for each model. (You can see and example in the MNIST/Training folder.) It would be useful to have robust conversion scripts that will work for any possible model, but that's something for the future.

**Comment by craigomac** [comment]
Could you share the script for splitting the Inception weights file? It would be particularly useful for those of us who've used a [retrained Inception model](https://www.tensorflow.org/tutorials/image_retraining).

**Comment by hollance** [comment]
I actually used the weights from the Apple Inception demo project. However, there is [this script](https://github.com/kakugawa/MetalCNNWeights) that you can use to convert Inception to Metal (assuming your model is in TensorFlow format, which it looks like it is).

**Comment by etown** [comment]
that script needs to be tweaked for the retrained inception model. has anybody got that the work?
